In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# read data from github: https://github.com/SachinScaler/ProbabilityAndStats_Nov2025
df_sachin = pd.read_csv('https://raw.githubusercontent.com/SachinScaler/ProbabilityAndStats_Nov2025/refs/heads/main/Sachin_ODI.csv')
df_sachin.head()

,runs,NotOut,mins,bf,fours,sixes,sr,Inns,Opp,Ground,Date,Winner,Won,century
0,13,0,30,15,3,0,86.66,1,New Zealand,Napier,1995-02-16,New Zealand,False,False
1,37,0,75,51,3,1,72.54,2,South Africa,Hamilton,1995-02-18,South Africa,False,False
2,47,0,65,40,7,0,117.50,2,Australia,Dunedin,1995-02-22,India,True,False
3,48,0,37,30,9,1,160.00,2,Bangladesh,Sharjah,1995-04-05,India,True,False
4,4,0,13,9,1,0,44.44,2,Pakistan,Sharjah,1995-04-07,Pakistan,False,False

In [3]:
df_sachin[["century","Won"]].value_counts()

century  Won
False    False    160
         True     154
True     True      30
         False     16
Name: count, dtype: int64

Q1. A match is randomly chosen, what is the probability that India have won that match?

In [4]:
df_sachin["Won"].value_counts()

Won
True     184
False    176
Name: count, dtype: int64

Q2. A match is chosen at a random, what is the probability that Sachin has scored a Century in that match?

In [6]:
df_sachin["century"].value_counts()

century
False    314
True      46
Name: count, dtype: int64

Q3: find out how many matches India have won when Sachin has scored a century

In [13]:
my_pivot = pd.crosstab(index=df_sachin['century'], columns=df_sachin['Won'],margins=True)
my_pivot

Won      False  True  All
century
False      160   154  314
True        16    30   46
All        176   184  360

In [14]:
# Get matches India won when Sachin didn't score a century using my_pivot
wins_without_century_from_pivot = my_pivot.loc[False, True]
print("Matches India won when Sachin didn't score a century (from my_pivot):", wins_without_century_from_pivot)

Matches India won when Sachin didn't score a century (from my_pivot): 154

In [15]:
# Matches India won when Sachin scored a century using my_pivot
wins_with_century_from_pivot = my_pivot.loc[True, True]
print("Matches India won when Sachin scored a century (from my_pivot):", int(wins_with_century_from_pivot))

Matches India won when Sachin scored a century (from my_pivot): 30

In [10]:
# Count matches India won when Sachin scored a century
count = df_sachin.loc[(df_sachin['century']) & (df_sachin['Won'])].shape[0]
print("Matches India won when Sachin scored a century:", count)

Matches India won when Sachin scored a century: 30

Q4. How many matches India have won when sachin didn't score a century.

In [12]:
# Matches India won when Sachin didn't score a century
wins_without_century = df_sachin.loc[(~df_sachin['century']) & (df_sachin['Won'])].shape[0]
print("Matches India won when Sachin didn't score a century:", wins_without_century)

Matches India won when Sachin didn't score a century: 154